export const generateAIReviewSummary = (reviews: any[]): string => {
  if (reviews.length === 0) {
    return "No reviews available yet.";
  }

  // This is a mock AI summary. In a real application, this would be generated by an AI service.
  const positivePoints = reviews.filter(review => review.rating >= 4).length;
  const totalReviews = reviews.length;
  const positivePercentage = (positivePoints / totalReviews) * 100;

  return `Based on the analysis of ${totalReviews} customer reviews, ${positivePercentage.toFixed(0)}% of customers had a positive experience with this product. Customers particularly appreciate the product's quality and value for money. Common praise includes the product's durability and ease of use. Some customers have suggested minor improvements in packaging and delivery times.`;
};